version: "3.9"

services:
  app_proxy:
    environment:
      APP_HOST: tomasrollo-prefect_server_1
      APP_PORT: 4200
      PROXY_AUTH_ADD: "false"

  ### Prefect Server API and UI
  server:
    image: prefecthq/prefect:2.11.2-python3.11
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/prefect:/root/.prefect
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    environment:
      # If you want to access Prefect Server from anywhere other than the Docker host machine, you will need to change
      # PREFECT_UI_URL to match the external hostname/IP used to load the  UI in your web browser.
      - PREFECT_UI_URL=http://127.0.0.0:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
#      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
      # Uncomment the following line if you want to use the 'S3 Bucket' storage block instead of the older 'S3' storage
      - EXTRA_PIP_PACKAGES=prefect-aws
    ports:
      - 4200:4200

  ## Prefect Worker
  worker:
    image: prefecthq/prefect:2.11.2-python3.11
    restart: on-failure
    stop_grace_period: 1m
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "worker", "start", "-t", "process", "-p", "server-work"]
    environment:
      - PREFECT_API_URL=http://server:4200/api
#       Use PREFECT_API_KEY if connecting the agent to Prefect Cloud
#     - PREFECT_API_KEY=YOUR_API_KEY
      - EXTRA_PIP_PACKAGES=prefect-aws

